### PR TITLE
Board Sub-Menu change

### PR DESCRIPTION
**Pull request by geraldjust**
Changed into Menu Sub-system added PSC Options for Board

### CODE REVIEW

**Comment by thomasonw** [comment]
Hey, this looks great - really like the use of the menus.   Some thoughts:

1) Maybe you would like to leave the 1st line like it was (with my name and original date), and add a 2nd line with you name / date /  and talk about how it was swizzled to support menus and control over PCS?

2) I am wondering, can support for the ATmegaxxC1's be added as well?  They are the same, but do not have the PCS subsystem.

3) And as to the name, at least for myself I tend to recognize `ATmegaxxM1/C1`  better then `ATmegaX1` - but that might be me...

**Comment by geraldjust** [comment]
Will do. I will change back to `ATmegaxxM1/C1` I can also add support for the ATmega32c1 and 64c1.
But i will need to point to the right bootloader file. And if i add them then there has to also be support in the avrdude.conf and any other files that rely on that.

**Comment by thomasonw** [comment]
IIRC, the bootloader files are the same, no change.  Perhaps I need to rename them to be more generic. 

 

I had not really looked closely at this stuff for years, an am noting I really did not have the C versions enabled, or at least not documented as so – even though they may well work just fine.   If it is an issue, perhaps just forget the C for now. 

 

But please do add your name as appropriate credit for the work you did!

**Comment by geraldjust** [comment]
Ah true, now that i think about it there should not be much of a difference for the bootloader.

Im sure its been a while. But this uC does have potential with the automotive CANBUS/LIN field. 

As for the C1, since the new m1-MZ variants are automotive grade with the higher temp range for operations. there isnt that much of a need for the C1 in that case.

Just updated it.

**Comment by thomasonw** [comment]
Yes, I agree with the C1 - part is not that popular in the channels, the M1 likely will be fine for most folks.

Is funny, this past year the port has gotten a bit more use from others.  Nice that it is helpful.  I am of course still using it for my Alternator Regulators, several hundred sold now!

Thanks for this great addition.

**Comment by thomasonw** [comment]
Guess one has to process the pull b4 closing it.

Next week I will assemble a zip lib and make a new version available with these changes.  Tks again, and good luck with your project!

**Comment by geraldjust** [comment]
Alternator Regulator? Hu, that sounds interesting. In a car situation? or a industrial application?

My project is a canbus enabled OLED screen to project information from a car onto a gauge. 
I prev made some but used the MCP2515. But though that if i could probably port the code to a chip with 64k and smaller footprint. It would solve a headache with space in my project enclosure, and with the MZ lowering the BOM. Still in the prototype phase. 
(Got the OLED working using the u8g2 lib!)

**Comment by thomasonw** [comment]
@geraldjust OLED screen?  Tell me more.   Alternator regulator is here:
[http://arduinoalternatorregulator.blogspot.com/](http://arduinoalternatorregulator.blogspot.com/)
and here:
[https://github.com/AlternatorRegulator](https://github.com/AlternatorRegulator)

Please drop me a note offline at: thomason.al --AT-- gmail.com     I would be most interested in the display you are building, perhaps can leverage it into the DC charging systems I am working on.

**Pull request merged**
